"""Synchronize the exhaustive static API reference with the Python source tree."""

from __future__ import annotations

import argparse
from pathlib import Path

from docs_inventory import (
    REPOSITORY_ROOT,
    build_cli_inventory,
    build_repository_inventory,
    build_inventory,
    render_cli_reference,
    render_module_page,
    render_symbol_index,
)

GENERATED_HEADER = (
    "<!-- Generated by scripts/gen_api_reference.py. Do not edit directly. -->\n\n"
)


def expected_pages() -> dict[Path, str]:
    """Return every generated reference path and its expected contents."""

    runtime_inventory = build_inventory()
    pages = {
        REPOSITORY_ROOT / "docs" / module.page_path: GENERATED_HEADER
        + render_module_page(module)
        for module in build_repository_inventory()
    }
    pages[REPOSITORY_ROOT / "docs" / "reference" / "cli-options.md"] = (
        GENERATED_HEADER + render_cli_reference(build_cli_inventory())
    )
    pages[REPOSITORY_ROOT / "docs" / "reference" / "python-symbols.md"] = (
        GENERATED_HEADER + render_symbol_index(runtime_inventory)
    )
    return pages


def generated_pages_on_disk() -> set[Path]:
    """Return generated reference pages currently present in the docs tree."""

    docs_dir = REPOSITORY_ROOT / "docs"
    return {
        path
        for path in docs_dir.rglob("*.md")
        if path.read_text(encoding="utf-8").startswith(GENERATED_HEADER)
    }


def check() -> int:
    """Report missing, stale, or unexpected generated pages."""

    expected = expected_pages()
    current = generated_pages_on_disk()
    issues: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            issues.append(
                f"Missing generated page: {path.relative_to(REPOSITORY_ROOT)}"
            )
        elif path.read_text(encoding="utf-8") != content:
            issues.append(f"Stale generated page: {path.relative_to(REPOSITORY_ROOT)}")
    for path in sorted(current - expected.keys()):
        issues.append(f"Unexpected generated page: {path.relative_to(REPOSITORY_ROOT)}")

    if issues:
        for issue in issues:
            print(issue)
        return 1
    print(f"Generated reference is current: {len(expected)} pages")
    return 0


def write() -> int:
    """Write every reference page and remove obsolete generated pages."""

    expected = expected_pages()
    for path in generated_pages_on_disk() - expected.keys():
        path.unlink()
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Synchronized {len(expected)} generated reference pages")
    return 0


def main() -> int:
    """Parse the synchronization mode and update or verify generated pages."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when generated references are stale",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
