"""MkDocs hooks that publish machine-readable documentation artifacts."""

from __future__ import annotations

import json
import os
import re
import subprocess
from functools import lru_cache
from pathlib import Path
from urllib.parse import urljoin

from docs_inventory import (
    REPOSITORY_ROOT,
    build_cli_inventory,
    build_inventory,
    build_repository_inventory,
    render_module_for_llms,
    render_module_page,
    render_cli_reference,
)

SOURCE_BRANCH_URL = "https://github.com/waybarrios/vllm-mlx/blob/gh-pages/"


@lru_cache(maxsize=1)
def _source_revision() -> str:
    """Return the immutable commit represented by this documentation build."""

    for candidate in (
        os.environ.get("VLLM_MLX_DOCS_SOURCE_REVISION", ""),
        os.environ.get("GITHUB_SHA", ""),
    ):
        if re.fullmatch(r"[0-9a-fA-F]{40}", candidate):
            return candidate.lower()
    completed = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPOSITORY_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    revision = completed.stdout.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError(f"Expected an immutable Git commit, received {revision!r}")
    return revision


def _pin_source_links(text: str, revision: str) -> str:
    """Replace mutable gh-pages source links with one commit permalink."""

    return text.replace(
        SOURCE_BRANCH_URL,
        f"https://github.com/waybarrios/vllm-mlx/blob/{revision}/",
    )


def on_page_markdown(markdown: str, **kwargs) -> str:
    """Pin every rendered GitHub source link to the build commit."""

    del kwargs
    return _pin_source_links(markdown, _source_revision())


def on_post_page(output: str, page=None, **kwargs) -> str:
    """Normalize search alternates and localized homepage presentation."""

    del kwargs
    canonical_url = getattr(page, "canonical_url", "")
    if canonical_url:
        output = re.sub(
            r'(<link\s+rel="alternate"\s+href=")([^"]+)'
            r'("\s+hreflang="[^"]+"\s*/?>)',
            lambda match: (
                f"{match.group(1)}"
                f"{urljoin(canonical_url, match.group(2))}"
                f"{match.group(3)}"
            ),
            output,
        )
    if 'class="vllm-hero"' not in output:
        return output
    return re.sub(
        r"\s*<a\b(?=[^>]*\brel=\"edit\")[^>]*>.*?</a>",
        "",
        output,
        count=1,
        flags=re.DOTALL,
    )


def _markdown_documents() -> list[Path]:
    """Return tracked hand-written documentation pages in stable order."""

    return sorted(
        path
        for path in (REPOSITORY_ROOT / "docs").rglob("*.md")
        if not path.read_text(encoding="utf-8").startswith(
            "<!-- Generated by scripts/gen_api_reference.py."
        )
    )


def on_post_build(config, **kwargs) -> None:
    """Write Markdown mirrors, the API inventory, and the full LLM corpus."""

    del kwargs
    site_dir = Path(config["site_dir"])
    docs_dir = REPOSITORY_ROOT / "docs"
    inventory = build_inventory()
    repository_inventory = build_repository_inventory()
    cli_inventory = build_cli_inventory()
    source_revision = _source_revision()

    full_parts = [
        "# vllm-mlx complete documentation",
        "",
        "> Complete human-authored documentation and static Python API inventory. "
        "Use `/llms.txt` for a compact index.",
        "",
    ]

    for source_path in _markdown_documents():
        relative = source_path.relative_to(docs_dir)
        content = _pin_source_links(
            source_path.read_text(encoding="utf-8").strip(), source_revision
        )
        mirror_path = site_dir / relative
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(content + "\n", encoding="utf-8")
        full_parts.extend(
            [
                f"# Documentation page: `{relative.as_posix()}`",
                "",
                content,
                "",
            ]
        )

    for module in repository_inventory:
        mirror_path = site_dir / module.page_path
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(
            _pin_source_links(render_module_page(module), source_revision),
            encoding="utf-8",
        )
        full_parts.extend(
            [_pin_source_links(render_module_for_llms(module), source_revision), ""]
        )

    symbol_index_source = docs_dir / "reference" / "python-symbols.md"
    symbol_index_mirror = site_dir / "reference" / "python-symbols.md"
    symbol_index_mirror.parent.mkdir(parents=True, exist_ok=True)
    symbol_index_mirror.write_text(
        _pin_source_links(
            symbol_index_source.read_text(encoding="utf-8"), source_revision
        ),
        encoding="utf-8",
    )

    cli_markdown = _pin_source_links(
        render_cli_reference(cli_inventory), source_revision
    )
    cli_mirror = site_dir / "reference" / "cli-options.md"
    cli_mirror.parent.mkdir(parents=True, exist_ok=True)
    cli_mirror.write_text(cli_markdown, encoding="utf-8")
    full_parts.extend([cli_markdown, ""])

    inventory_payload = {
        "schema_version": "1.0",
        "repository": "waybarrios/vllm-mlx",
        "source_branch": "gh-pages",
        "source_revision": source_revision,
        "module_count": len(inventory),
        "symbol_count": sum(len(module.symbols) for module in inventory),
        "modules": [module.to_dict() for module in inventory],
    }
    (site_dir / "api-inventory.json").write_text(
        _pin_source_links(
            json.dumps(inventory_payload, indent=2, ensure_ascii=False),
            source_revision,
        )
        + "\n",
        encoding="utf-8",
    )
    source_inventory_payload = {
        "schema_version": "1.0",
        "repository": "waybarrios/vllm-mlx",
        "source_branch": "gh-pages",
        "source_revision": source_revision,
        "module_count": len(repository_inventory),
        "symbol_count": sum(len(module.symbols) for module in repository_inventory),
        "source_roots": ["vllm_mlx", "scripts", "examples"],
        "modules": [module.to_dict() for module in repository_inventory],
    }
    (site_dir / "source-inventory.json").write_text(
        _pin_source_links(
            json.dumps(source_inventory_payload, indent=2, ensure_ascii=False),
            source_revision,
        )
        + "\n",
        encoding="utf-8",
    )
    (site_dir / "cli-inventory.json").write_text(
        _pin_source_links(
            json.dumps(
                {
                    "schema_version": "1.0",
                    "repository": "waybarrios/vllm-mlx",
                    "source_branch": "gh-pages",
                    "source_revision": source_revision,
                    "option_count": len(cli_inventory),
                    "options": [option.to_dict() for option in cli_inventory],
                },
                indent=2,
                ensure_ascii=False,
            ),
            source_revision,
        )
        + "\n",
        encoding="utf-8",
    )
    (site_dir / "llms-full.txt").write_text(
        "\n".join(full_parts).rstrip() + "\n", encoding="utf-8"
    )
